elixirkoans/elixir-koans

- lib/blank_assertions.ex
- lib/koans.ex
This is done by wrapping the ExUnit assertions that we use. Instead of calling ExUnit straight, the `BlankAssertions` module intercepts calls and does one of two things:
* If the assertion contains a blank, it is failed immediately. ExUnit is never called and the failing expression is printed
* If the assertions does not contain a blank, just delegates to ExUnit and lets it handle the assertion.
> Add support for blanks in assertions

- lib/display.ex
- lib/watcher.ex
This PR changes the error formatting for compiler errors:
* Only print the first two lines of the stacktrace to hide the runner internals from the trace.
* It doesn't print the message about workers shutting down. That message is not useful to users.
Closes #4
> Intercept and print compile errors in a nicer way.

- lib/display.ex
- lib/koans.ex
- lib/runner.ex
Inspired by plug.
This works by `accumulating` the name of each koan into an attribute and
then defining a new function `all_koans` that returns that list.
When meditating we use `all_koans` instead of `module.__info__(:functions)`.
> Force koan order using macros and attributes

- lib/display.ex
- lib/koans.ex
- lib/watcher.ex
Tried to get a consistent look to assertion errors and runtime errors.
cc @felipesere 
closes #30
> Format runtime errors consistently with assertion errors

- lib/display.ex
- lib/options.ex
- lib/runner.ex
- test/options_test.exs
The default is still to run `Equalities`.
If the name of the module is not known, an error and possible modules are shown in red:
@Maikon @ukutaht
> Introduce --koan=<name> to run a specific koan module.

- lib/display.ex
- lib/execute.ex
- lib/runner.ex
- test/executor_test.exs
- test/koans_harness_test.exs
- test/support/passing_koan.ex
This PR is necessary to build good Agents and Supervisior koans.
It changes the way we run koans from single process for all modules, to a individual process per _koan_.
That way, anything process that is started with a _link_ will be torn down after the koan.
It also splits _executing_ a koan from _running all koans_. The former has no dependencies, the latter depends on `Display` and `Options`.
A large chunk of credit goes to @marosluuce :+1: 
@ukutaht 
@Maikon
> Koan per process

- lib/koans/05_maps.ex
- test/koans/enum_koans_test.exs
- test/koans/equalities_koan_test.exs
- test/koans/functions_koans_test.exs
- test/koans/maps_koans_test.exs
- test/koans/patterns_koans_test.exs
- test/koans/processes_koans_test.exs
- test/koans/strings_koan_test.exs
- test/koans/tasks_koans_test.exs
- test/koans/tuples_koans_test.exs
This is _super_ pedantic, but I noticed an inconsistency in this style in the code, and I happen to prefer it this way 😆 (makes the git history cleaner when appending elements).
Feel free to ignore! 😅💦
> Add trailing commas to multi-line lists and maps

- lib/koans/06_structs.ex
Little change to remove some ambiguity in the koans. `|>` is he pipe operator, but `|`, in `erlang/elixir` is the 'cons' operator (short for constructor).
> Struct koans now calls '|' operator by correct name: 'cons'

- lib/koans/06_structs.ex
- test/koans/structs_koans_test.exs
I think is better to continue use safe ```Map.fetch``` until we familiarize users with dangerous function concept.
Not every body comes from ruby background, with knowledge of ```?``` and ```!``` function notations.
> Map.fetch! -> Map.fetch in 06_structs.ex

- test/test_helper.exs
Currently, answers are zipped with the list of koans which might allow examples to go untested. This admittedly inelegant solution ensures that you at least provide an answer for each koan. It should provide a good sanity check while TDDing koans.
Honestly I'm not a huge fan of this solution, but it was simple enough to implement and serves to start a conversation about answers. 😃
> Error is raised if an answer isn't provided for each koan

- lib/display.ex
- lib/meditate.ex
- lib/tracker.ex
- lib/watcher.ex
- test/tracker_test.exs
I worked through the entire set of koans and it took me a moment to realize that the last one wasn't stuck. It's because the process never exits (`:timer.sleep(:infinity)`). This restructures the code to print a nice little message when the entire run completes either initially or in the watcher.
I'd like to add tests around all these things, but the tests seem to be a little slim over the supporting code, so I opted to pass for now and test manually instead.
> Congratulate and exit when koans are complete

- lib/koans.ex
- test/test_helper.exs
Currently failing koans cause the parent process to hang while waiting for results. This sends failures back to the parent process and assert that everything passed.
> Assert koan test results

- mix.exs
The project unfortunately does not compile in elixir version 1.2.0. That major version got released with a bug in ExUnit that fails when assertions are used within macros which we rely heavily on. For users on 1.2.0, this led to a compile error `undefined function answer/0`. This issue is [fixed](https://github.com/elixir-lang/elixir/releases/tag/v1.2.1) in 1.2.1 so that's the minimum we should require.
> Ensure elixir version is at least 1.2.1

- lib/blanks.ex
- lib/koans/10_processes.ex
- test/blanks_test.exs
- test/koans/processes_koans_test.exs
I sort of stumbled upon the fact that `assert_receive` isn't working as expected in the koans. It's proven by this typo. I'm not yet sure what the problem is, but I'm assuming it's something to do with the various metaprogramming that's happening amongst these macros... I'll keep working on it, but any input is welcome!
> Problem with assert_receive in koans

- lib/koans/05_maps.ex
- test/koans/maps_koans_test.exs
At this point, the learner hasn't seen functions, the Enum module, or
the pipe operator, so it feels like a little much to add that here. The
reason it's needed is that the order of keys/1 and values/1 is reverse
of how it's defined. This is due to an implementation detail in Erlang's
maps. We /could/ use this as a learning opportunity rather than sorting
them, but I'm not sure what could be said about that...
Other options include
- get rid of the example
- limit example to single key and value to avoid order problems
- use it as a learning opportunity (what do we learn?)
> Replace pipeline with composed function in maps koan

- lib/koans.ex
Instead of accessing multiple answers via `elem(converted, id)` I've changed the koan macro to just destruct the answers in the test function signature. This way all answers become variables on their own and can be pinned in our special `assert_receive` handling. This PR doesn't include an example of using this but I've confirmed that it works with the `yelling_echo_loop` from #98.
closes #94
> Allow multiple answers in pinned context

- lib/meditate.ex
This change makes meditate task visible when user runs `mix help`.
> Add meditate shortdoc to display task in mix list

- lib/watcher.ex
Should solve #96 by stripping away the IntelliJ specific suffix.
> Strip off IntelliJ specific extension from reloaded files.

- lib/koans/10_enums.ex
- test/koans/enum_koans_test.exs
Zipping atoms and numbers creates an opportunity for the learner to
realize "💡 I just made a keyword list!"
> Swap order of zipped lists to create learning opportunity

- lib/display.ex
- lib/execute.ex
- lib/koans.ex
- lib/koans/01_equalities.ex
- lib/koans/02_strings.ex
- lib/koans/03_atoms.ex
- lib/koans/04_tuples.ex
- lib/koans/05_lists.ex
- lib/koans/06_keyword_lists.ex
- lib/koans/07_maps.ex
- lib/koans/08_structs.ex
- lib/koans/09_pattern_matching.ex
- lib/koans/10_functions.ex
- lib/koans/11_enums.ex
- lib/koans/12_processes.ex
- lib/koans/13_tasks.ex
- lib/koans/14_agents.ex
- lib/runner.ex
- lib/tracker.ex
- test/executor_test.exs
- test/support/passing_koan.ex
- test/support/sample_koan.ex
- test/tracker_test.exs
To help build more of a story into the koans,
I've added a module attribute called `@intro`.
That intro will be displayed the very first time a module is accessed.
> Adds an @intro attribute to display when running a module

- lib/runner.ex
The sigil tests were not listed in "runner.ex".
> Make Sigil tests run

- lib/display/colours.ex
- lib/display/failure.ex
Show left and right hand values when equality fails
For assertions that contain function calls, displaying just the
expression is not helpful. For e.g.
Assertion failed
String.upcase("foo") == "Foo"
The learner is given no extra information to help them learn. Sure they
might consult the documentation (and should!), but perhaps a better
experience would be for us to inform the learner about the values it
encountered.
Assertion failed
String.upcase("foo") == "Foo"
left:  "FOO"
right: "Foo"
Learner: 💡 ah hah! it upcases the whole string! 💫
One might argue that this reveals too much information/makes it too easier. This has not been my experience in pairing with learners. What do you think?
> Display inequality, guide learner

- lib/blanks.ex
- lib/koans.ex
No functional changes here. Just some tweaks.
> A few small things I came across

- lib/watcher.ex
Ignore, for example, temporary swap files created by an editor.
Otherwise you see errors like this:
```
** (Code.LoadError) could not load /home/bc/elixir-koans/lib/koans/.02_strings.ex.swx
(elixir) lib/code.ex:657: Code.find_file/2
(elixir) lib/code.ex:319: Code.load_file/2
** (UnicodeConversionError) invalid encoding starting at <<222, 123, 87, 62, 37, 42, 0, 122, 46, 0, 0, 98, 99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>
(elixir) lib/string.ex:1746: String.to_charlist/1
(elixir) src/elixir_compiler.erl:45: :elixir_compiler.file/2
** (Code.LoadError) could not load /home/bc/elixir-koans/lib/koans/.02_strings.ex.swp
(elixir) lib/code.ex:657: Code.find_file/2
(elixir) lib/code.ex:319: Code.load_file/2
```
> Only run elixir files

- .travis.yml
- mix.exs
This will require the version to be at least 1.3 and less than 1.4. I'm assuming that most people using this aren't bound to a specific, older version and will be able to update. We'll have to revisit this when 1.4 comes out, but at that point we'd probably want to update the travis build anyway.
> Bump elixir version.

- lib/blanks.ex
Just a few small clean ups. The only thing I'm not completely confident with is the removal of the `:do` function heads. I suppose this works because the Macro.prewalk used further down the call stack can account for it?
> A few tweaks to Blanks

- lib/display/colours.ex
- lib/display/failure.ex
- test/display/failure_test.exs
This formats match failures to provide clearer learner feedback. ExUnit has a [special case](https://github.com/elixir-lang/elixir/blob/3b499ffb87269d3fa7c874e1deb55b3a30435027/lib/ex_unit/lib/ex_unit/assertions.ex#L145-L158) for `match?`. Also, I went ahead and added tests around inequality failures and it caught a missing interface on the test painter! 💫 
[Closes #144]
> Format match failures

- test/display/failure_test.exs
- test/support/single_arity_koan.ex
This is the best that could come up with to deal with #153 
It does fail when the `do: ` is missing, but it is not immediately obvious...
@iamvery what do you think? Something to pivot on?
> Test for single arity failures

- lib/display/colours.ex
- lib/koans/15_processes.ex
- lib/tracker.ex
- mix.exs
- mix.lock
This should fix all the warnings from Elixir 1.4 like:
> warning: variable "..." does not exist and is being expanded to "...()", please use parentheses to remove the ambiguity or change the variable name
h/t @dylan-chong #157
> Fix Elixir 1 4 warnings

- lib/watcher.ex
Fixing: https://github.com/elixirkoans/elixir-koans/issues/138
By normalizing first we remove the IntelliJ specific suffix if it is
present which allows the ".ex" extension to correctly match IntelliJ
edited files.
> Normalize the file before calling reload.

- lib/koans/13_functions.ex
otherwise the `greet/1` will be called
https://github.com/elixirkoans/elixir-koans/blob/master/lib/koans/13_functions.ex#L6-L8
@dillonkearns
> should call anonymous function with dot

- lib/koans/16_tasks.ex
Technically either way works, but I'm assuming this was just a little typo.
> Fix comma placement typo

- lib/koans/15_processes.ex
Should clarify #166 
`receive do; end` blocks the spawned thread so it's guaranteed to be alive when we assert.
> Just 'nil' might have lived long enough, 'receive' definitly does.

- lib/koans/07_keyword_lists.ex
- lib/koans/12_pattern_matching.ex
- test/koans/patterns_koans_test.exs
Koan 7.3 is not clear. Updated to make it generic and use List module instead of pattern matching (which is not yet introduced to the learner)
> Fetching values of repeated key in keywordlist

- lib/koans/13_functions.ex
It's more idiomatic and that syntax was introduced two koans earlier, so it should be OK to use it.
> Use more succinct syntax for mapping with String.capitalize

- lib/koans/09_map_sets.ex
Small grammar fix for `MapSet` koan (09).
> Fix comma placement

- lib/koans/09_map_sets.ex
- test/koans/map_sets_koans_test.exs
specifically, before it is used to show sets do not have duplicates
Edit: Instead, remove the later `MapSet.size/1` koan as the function is sufficiently introduced by `koan "However, I do not allow duplication"`.
> introduce MapSet.size/1 earlier

- lib/koans/13_functions.ex
- test/koans/functions_koans_test.exs
Add new koan after discussion in Github issue: 
https://github.com/elixirkoans/elixir-koans/issues/222#issuecomment-399979891
[quote]
And, in fact, you can define multiple cases for a function using this sytnax:
```
lolwat = fn
"lol" -> "wat"
_ -> "haha"
end
lolwat.("lol")
lolwat.("anything")
lolwat.("rly")
```
[/quote]
> Add koan "You can use pattern matching to define [...]"

- lib/koans/20_comprehensions.ex
- test/koans/comprehensions_koans_test.exs
The koans added here introduce comprehensions. (the `for` keyword.)
"Koans for special forms" https://github.com/elixirkoans/elixir-koans/issues/53
> Add new koans for comprehensions

- lib/watcher.ex
Fixes Watcher/Autorunner for some editors (ex: TextMate)
---
Woo, creating PRs before even meditating
> Fixes Watcher/Autorunner for some editors (ex: TextMate)

- lib/watcher.ex
This function was replaced by Code.compile_file/1 and is deprecated with
planned removal in 1.9.
See: https://github.com/elixir-lang/elixir/pull/7201
Noticed this when looking into #228
> Replace deprecated call to Code.load_file/1

- .dockerignore
- Dockerfile
- docker.sh
Really like the work you guys are doing here! I don't have elixir installed locally so I use docker for my projects. Thought I would contribute the Dockerfile and commands I have been using. From within the elixir-koans directory:
```
docker build -t elixir-koans . && docker run --rm -v `pwd`:/elixir-koans -ti elixir-koans
```
I would be happy to update the README with these commands. Thanks!
> Koans for Docker users

- lib/watcher.ex
A deprecation warning in Elixir 1.7 was fixed in #229, however I failed to notice that the new function being used is unavailable in older Elixirs. This should work on Elixirs old and new.
[closes #230]
> Make code loading compatible and deprecation free on old and new elixirs

- README.md
Might just be a small thing (and a complete lack of ☕️ in the morning), but I was missing the very first instruction in the README to actually clone the repo first, before running `mix deps.get` 🤦‍♂.
> Add cloning the repo as a first step to the README

- docker.sh
Mounting the whole project as part of the docker run command means that the mix deps performed in the Dockerfile has the installation wiped out by mounting the local project directory (which does not include the deps directory since that was only inside the container when mix deps was performed during the docker build).
The error shows up as dependencies not being available when the container is actually run.
```
♥ $ ./docker.sh
Sending build context to Docker daemon  639.5kB
Step 1/7 : FROM elixir:1.5
---> 2d2fdf265444
Step 2/7 : RUN apt-get update && apt-get install -y inotify-tools
---> Using cache
---> f05c90e095eb
Step 3/7 : WORKDIR /elixir-koans
---> Using cache
---> e9a5c4bf803c
Step 4/7 : ADD . /elixir-koans/
---> 708161a5a47c
Step 5/7 : RUN mix local.hex --force
---> Running in …
```
> Mount only the koans directory, not the whole project

- lib/execute.ex
- lib/koans.ex
- test/display/failure_test.exs
- test/koans/comprehensions_koans_test.exs
**Changes in getting a stacktrace from a failed koan**
As of Elixir 1.10, the usage of `System.stacktrace` to retrieve a stacktrace is now deprecated and is also non functional. Refer to the [docs](https://hexdocs.pm/elixir/System.html#stacktrace/0).
#242 tried substituting `System.stacktrace` with Erlang's `:erlang.get_stacktrace()` but it returns an empty list instead.
So, I substituted the calling of `System.stacktrace` in a non rescue context when trying to report errors with a call to `__STACKTRACE__` in the Koan macro itself, for normal execution and for tests, something that #242 suggested.
**Making the tests pass**
Even then, the tests would not pass. Two tests were failing.
The failure_test.exs was providing input arguments which were not correct for the output the tests …
> Change usage of System.stacktrace into __STACKTRACE__ and make tests pass

- lib/koans/07_keyword_lists.ex
- lib/koans/10_structs.ex
- test/koans/keyword_lists_koans_test.exs
Koan description refers to the values of the key in a keyword list, so it should be asserting for a list of values.  
Also remove some duplication of struct defaults, %Plane already has `maker: boeing` default.
> Mismatch on koan description and assertion in 07_keyword_lists

- lib/koans/03_numbers.ex
- lib/meditate.ex
Shows up when running mix meditate:
`warning: not passing the :switches or :strict option to OptionParser is deprecated`
Shows up when running mix test:
`warning: Range.range?/1 is deprecated. Pattern match on first..last instead`
> Fix deprecation warnings

- lib/koans/19_protocols.ex
I think when struct S implements protocol P, we can say S is P or S has trait of P.
For example, List implements Enumerable and we can say List is Enumerable.
In current example, Musician implements School, but we can't say Musician is School.
I think better abstraction where Musician, Dancer belongs to and Baker doesn't is Artist.
> Change protocol examples

- lib/koans/09_map_sets.ex
`Enum.fetch(@set, 0)` usage should be discouraged as it only works for MapSet created with list size < 32.
So I think that koan should be removed.
> Remove Enum.fetch usage for MapSet

- lib/runner.ex
- lib/watcher.ex
Things like flycheck-elixir in Emacs can create temporary files in the
same directory as the upstream files that contain the koans, with a
"flycheck_" prefix but still ending in ".ex". This change makes it so
that we skip such files.
> be stricter about which files to watch

- lib/koans/15_processes.ex
[closes #266]
Failure was confusing in #266.
Add message to nudge learner in the right direction.
```
Processes
Now meditate upon Processes
|                              | 0 of 36
----------------------------------------
A common pattern is to include the sender in the message, so that it can reply
Assertion failed in lib/koans/15_processes.ex:83
Sorry, I didn't get the right message. Look at the message that is sent back very closely, and try again
```
> Add helpful message when processes koan assertion fails

- lib/koans/15_processes.ex
Reported in #275
Example suggests order is important, but fails to check that in how it is written.
Refactor example to explicitly receive messages and assert the order in which they are received.
> Fix example to actually check message order as desc suggests

- config/config.exs
```sh
➜  elixir-koans git:(master) mix deps.get
warning: use Mix.Config is deprecated. Use the Config module instead
config/config.exs:1
```
Mix.Config is deprecated (see [here](https://hexdocs.pm/elixir/1.14.3/Config.html#module-migrating-from-use-mix-config))
> fix(config): replace deprecated Mix.Config by Config

- .github/workflows/elixir.yml
Fixing the issue pointed out in [this GitHub workflow execution](https://github.com/elixirkoans/elixir-koans/actions/runs/4314335021/jobs/7527274281)
We would be able to use ubuntu-22.04 when upgrading the OTP version to, at least, 24.2 (see [here](https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp))
> fix(ci): pin ubuntu-20 to run github actions

- .github/workflows/elixir.yml
- lib/display.ex
- lib/display/progress_bar.ex
- test/display/progress_bar_test.exs
This fixes the issues I observed while solving the koans. Some of the issues I noticed are:
- Random vertical position of printing koans
- Sometimes koan intro printed before clear screen
- Next koan does not appear when all koan passes for a module
> Fix inconsistent printing of meditation

- Dockerfile
Hey there!
I bumped into an issue when building the current Dockerfile. A 404 error happens when fetching the stretch release from the Debian repo:
This is happening because the base Docker image depends on the stretch release living on the [regular Debian repo](https://ftp.debian.org/debian/dists/), which has now been moved to the [archived one](https://archive.debian.org/debian/dists/). Bumping the image version fix this issue.
Also, I'd just like to say I really loved the work done on introducing Elixir to newcomers in this repo. Awesome stuff! ❤️
> fix(docker): bump elixir image version
