- lib/koans/lists.ex
- mix.exs
@heruku 
Initial draft for lists koans. Suggestions and ideas for names, additional koans, modification of existing or anything else, are welcomed.
> Add List koans

- lib/koans/03_maps.ex
I want to start a discussion on what methods should be taught in the koans.
Once that is settled I will re-rewrite the examples to be more realistic, probably working on a map that represents a person.
> WIP: Start work maps

- lib/koans/05_functions.ex
- lib/runner.ex
> Koans for Elixir functions.

- lib/koans/06_enum.ex
- lib/runner.ex
Have a look at the selection of methods from Enum in this PR.
I will make the koans themselves more 'story' like before merging.
> WIP: Basic koans for the Enum module.

- lib/koans/07_arithmetic.ex
- lib/runner.ex
Basic koans for arithmetic. I was expecting more here...
> Koans for basic arithmetic

- lib/blank_assertions.ex
- lib/koans/09_pattern_matching.ex
- lib/runner.ex
> Start basic pattern matching koans

- lib/blank_assertions.ex
- lib/display.ex
- lib/koans.ex
- lib/koans/10_processes.ex
- lib/koans/11_task.ex
- lib/meditate.ex
- lib/runner.ex
~~Includes fairly clunky infrastructure to show the right line number when a blank assertion fails.~~
> Koans about processes.

- lib/koans/05_functions.ex
- lib/koans/09_pattern_matching.ex
Here's some ideas for exposing these ideas in a simple way. Open to feedback of course.
> WIP Feedback

- lib/blank_assertions.ex
- lib/koans/03_maps.ex
- lib/koans/04_strings.ex
- lib/koans/05_functions.ex
- lib/koans/06_enum.ex
- lib/koans/07_arithmetic.ex
- lib/koans/08_structs.ex
- lib/koans/09_pattern_matching.ex
- lib/koans/10_processes.ex
- lib/koans/11_task.ex
- lib/koans/12_tuples.ex
- test/koans_harness_test.exs
> Extract answers

- lib/runner.ex
- lib/watcher.ex
> Ensure that watcher does not try to run a module that is not a koan

- lib/koans/06_maps.ex
- test/koans_harness_test.exs
> Sort the result from #keys and #values to make the result more obvious.

- lib/koans/03_strings.ex
- lib/koans/06_maps.ex
- test/koans_harness_test.exs
@marosluuce In response to your feedback from Friday. If you think there's more to do here, feel free to push a commit on top of this :)
> Attempt at making maps easier to go through

- lib/koans/14_agents.ex
- lib/runner.ex
- test/koans_harness_test.exs
> Koans for agents

- lib/blank_assertions.ex
- lib/koans.ex
It needed to be turned into a macro and some tinkering with
external vars was needed.
> Fixes the reported line for failures using assert_receive

- lib/blank_assertions.ex
- lib/display.ex
Calling macros within macros seems to not work out as I want. I just built my own quick version of `assert_receive`
@Maikon @ukutaht
> Implement a custom version of assert_receive.

- lib/koans/04_lists.ex
- lib/koans/05_maps.ex
- lib/koans/06_structs.ex
- lib/koans/08_functions.ex
- lib/koans/09_enums.ex
- lib/koans/10_processes.ex
- lib/koans/11_tasks.ex
- lib/koans/12_agents.ex
Hi @ukutaht and @felipesere !
I finished the koans now and found a few typos along the way, so I thought I'd raise a PR to fix those.
I'll have a think on what else I can improve and might even try to add a koan once I understand the language a bit better...
Overall I thought they were really good though. Everything made sense and I only found "Processes" and "Tasks" a bit difficult to figure out (although maybe that was just me...).
I hope this PR is ok - let me know if you want me to change anything back...
> fixes typos and some formatting

- lib/koans/07_pattern_matching.ex
- lib/koans/10_processes.ex
Couple small things. There was also "levelling the playing field" which my computer (and myself) thought was a typo. It seems like it also may be part of my North American english. Happy to send that along as well if it is indeed a fix.
> Some grammar changes

- lib/koans/05_maps.ex
- lib/koans/06_structs.ex
- lib/koans/07_pattern_matching.ex
- lib/koans/08_functions.ex
- lib/koans/09_enums.ex
- lib/koans/11_tasks.ex
This is a tiny modification!
I have updated the maps and lists to make the code look more consistent based on the documentation.
- [List documentation](http://elixir-lang.org/docs/stable/elixir/List.html)
- [Map documentation](http://elixir-lang.org/docs/stable/elixir/Map.html)
> Modify lists and maps style

- test/blanks_test.exs
- test/executor_test.exs
- test/koans/enum_koans_test.exs
- test/koans/equalities_koan_test.exs
- test/koans/functions_koans_test.exs
- test/koans/lists_koans_test.exs
- test/koans/maps_koans_test.exs
- test/koans/patterns_koans_test.exs
- test/koans/processes_koans_test.exs
- test/koans/strings_koan_test.exs
- test/koans/structs_koans_test.exs
- test/koans/tasks_koans_test.exs
- test/koans/tuples_koans_test.exs
- test/test_helper.exs
This should not change the any behavior or tests. Purely a refactor to make the tests clearer.
> Refactor blanks tests

- lib/koans/07_pattern_matching.ex
- test/koans/patterns_koans_test.exs
@RabeaGleissner @felipesere Do you think this is a better demonstration of the pin operator?
> Attempt clarifying the pin operator

- test/koans/agents_koans_test.exs
Noticed that the agents koans didn't have tests. Here they are 👍
> Add test for agents koans

- lib/display.ex
- lib/execute.ex
- lib/meditate.ex
- lib/runner.ex
- lib/tracker.ex
- lib/watcher.ex
- test/display_test.exs
- test/tracker_test.exs
*Updated*
Here is my new stab, with simpler code and better handling of `--koan=Agents`:
I wonder if we should a) add colors b) add a way to tell that you skipped X amount of koans.
> Add a progress bar

- lib/colours.ex
- lib/display.ex
- lib/meditate.ex
> Cleanup display

- lib/koans/07_pattern_matching.ex
- lib/koans/08_functions.ex
- lib/koans/10_processes.ex
- test/koans/functions_koans_test.exs
- test/koans/patterns_koans_test.exs
I made a bunch of notes working through the set of koans early last week. I'm going to push changes here for discussion. I'm happy to spin off separate PRs if necessary 😅
> Update various koans

- lib/koans/09_enums.ex
Just a small change to a couple examples to make the behavior more clear.
> Tweak enum koan

- lib/koans/04_lists.ex
- test/koans/lists_koans_test.exs
> Add wrapping list koan

- lib/koans/08_functions.ex
It felt like it would be nice to provide a little better description about what's happening with pipe. Legit?
> Update description of piping

- lib/koans/06_maps.ex
- lib/koans/08_pattern_matching.ex
- lib/koans/09_functions.ex
- lib/koans/10_enums.ex
- lib/koans/11_processes.ex
- lib/koans/12_tasks.ex
- test/koans/functions_koans_test.exs
- test/koans/maps_koans_test.exs
Here are various improvements regarding styleguides and wordings. Would love feedbacks!
> Improvements suggestions

- README.md
- lib/options.ex
- test/options_test.exs
As multiple people have said, we should make clearing the screen the default.
@ukutaht @iamvery @Maikon @gemcfadyen what is your opinion?
> Make clearing the screen the default

- lib/koans/10_pattern_matching.ex
- test/koans/patterns_koans_test.exs
I thought we needed a more explicit example about pattern matching and pinning.
@ukutaht @Maikon @iamvery @gemcfadyen @RabeaGleissner
> Move pinning to the back of the kaon and enhance example

- lib/koans/08_keyword_lists.ex
I think this makes the sentence read more clearly.
> Fix grammar omission

- lib/koans/02_strings.ex
- test/koans/strings_koan_test.exs
When learning about the behavior of a function, in general the learning
experience is better when provided with the input and asked for the
output.
This was felt while pairing on the koans with a learner. These particular examples felt slightly confusing as is for some reason. Of course, I do realize these aren't the only examples arranged in such a way, so we might consider rearranging them all. Alternatively, it might make sense to approach on a per example basis.
> Prefer function output over input

- lib/koans/07_lists.ex
- test/koans/lists_koans_test.exs
Add clarity for List.delete and List.wrap
> List koans

- lib/koans/08_keyword_lists.ex
- test/koans/keyword_lists_koans_test.exs
Clarify keyword list as options example by including else clause
> Keyword List update

- lib/execute.ex
The previous strategy wasn't robust enough to detect typos in function
calls. For example, if you misremembered String.duplicate/2 as
String.repeat/2 the koan runner would hang and have to be restarted.
This is because the stacktrace for an error like that doesn't have line
numbers. To avoid the problem, we detect the first pieces of the
stracktrace that is in the koan module. I can't decide if that's a
perfect solution, but it seemed to work in my testing. Hoping to get
other's feedback.
Before the change such an error would look like:
```
● HEAD ~/Code/OSS/elixir-koans » mix meditate --no-clear-screen
Compiled lib/options.ex
Compiled lib/runner.ex
Compiled lib/koans/01_equalities.ex
Welcome to the Elixir koans.
Let these be your first humble steps towards learning a new language.
The …
```
> Refactor error expansion to locate errors in koan module

- lib/koans.ex
Noticed these functions were no longer being used. ✂️
> Remove unused private functions

- lib/koans/13_functions.ex
- test/koans/functions_koans_test.exs
I thought it might be interesting to show a couple more examples to demystify the & operator.
> Anonymous functions using & for arbitary expressions

- lib/koans.ex
It's a bummer that this isn't tested. I spent just a couple minutes trying to come up with where to put the test, but gave up for time's sake. I'd love to hear some ideas for making sure this doesn't regress again!
See https://github.com/elixirkoans/elixir-koans/issues/151 for more information and screenshots.
[Closes #151]
> Properly unwrap the koan body the keyword list argument

- CONTRIBUTORS.md
- lib/koans/11_structs.ex
- test/koans/structs_koans_test.exs
> Demonstrate put_in to manipulate nested struct values

- lib/koans/10_map_sets.ex
- test/koans/map_sets_koans_test.exs
> Whitespace

- lib/koans/10_map_sets.ex
- test/koans/map_sets_koans_test.exs
> Tweaks to #170 MapSet example

- lib/koans.ex
- mix.exs
I would love to have the koans run against the Elixir master build, but that doesn't appear to be a valid Elixir version in the TravisCI configuration 😞 
[Closes #177]
[Closes #167]
> Loosen version restriction on project

- .travis.yml
- mix.exs
@iamvery or @ukutaht merge this if you agree 😄
> Use Elixir 1.3 as the new minimum bar

- lib/koans/02_strings.ex
- test/koans/strings_koan_test.exs
I'm really not sure about the wording. I'm not a native English speaker, and believe that someone will be able to find a better text for this that will also fit with the rest of the nice koans.
[Closes #184]
> Add string interpolation koan. Fix #184

- lib/koans/04_numbers.ex
- test/koans/numbers_koans_test.exs
> Remove 'I think I need my number as a char' koan. Fix #176

- lib/display/progress_bar.ex
Noticed small typo in function name of Display.ProgressBar
> Correct spelling of function in Display.ProgressBar

- lib/runner.ex
- test/runner_test.exs
> Get lessons order from filenames. Fix #196

- lib/koans/08_maps.ex
@person module attribute can be used instead
> Removed useless 'initial' var

- .travis.yml
This was suggested in PR #209.
> Add elixir 1.5.2 to travis tests matrix

- .travis.yml
- lib/elixir_koans.ex
- lib/watcher.ex
- mix.exs
- mix.lock
I was going through the koans again (I found myself really needing a refresher) and happened to notice the old package was still in here.
I took a crack at converting it and I did a bit of very basic testing.
Please let me know if there are other changes you would like to see or specific testing I should do.
> Convert from ExFSWatch to FileSystem

- lib/koans/07_keyword_lists.ex
- lib/koans/10_structs.ex
- lib/koans/12_pattern_matching.ex
- lib/koans/13_functions.ex
- test/koans/functions_koans_test.exs
- test/koans/keyword_lists_koans_test.exs
- test/koans/patterns_koans_test.exs
- test/koans/structs_koans_test.exs
> Minor koan rearrangement

- lib/koans/03_numbers.ex
- test/koans/numbers_koans_test.exs
> more number koans

- README.md
- lib/koans/11_sigils.ex
- lib/koans/18_genservers.ex
I did some chores: removed occasional trailing whitespaces, added newline at the end of the file/etc, removed double newline at the end of the file.
Signed-off-by: Vyacheslav Bikbaev <la.sintez@gmail.com>
> chore: removed trailing whitespaces, added newline

- lib/koans/18_genservers.ex
- test/koans/genservers_koans_test.exs
This truth is self-evident from the other koans.
[Closes #236]
> Remove duplicative koan

- lib/koans/03_numbers.ex
- lib/koans/12_pattern_matching.ex
- lib/koans/13_functions.ex
- test/koans/functions_koans_test.exs
Just a tiny improvement I felt could be made while completing these. Thank you for keeping the ruby koans tradition alive 😄
> Highlight that Float functions returns float
